version: '3'
name: instagram-by-kotlin
services:
    mysql:
        container_name: flatagram_mysql
        image: mysql:latest
        ports:
          - "3306:3306"
        environment:
          - MYSQL_ROOT_PASSWORD=1234
          - MYSQL_DATABASE=flatagram
          - MYSQL_USER=flatagram
          - MYSQL_PASSWORD=1234
        volumes:
          - mysqldb:/var/lib/mysql
        restart: unless-stopped
    redis:
        container_name: flatagram_redis
        image: redis:7.0.11
        ports:
          - "6379:6379"
        volumes:
          - ./redis/data:/data
          - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
        restart: always
        labels:
          - "name=redis"
          - "mode=standalone"
        command: redis-server /usr/local/conf/redis.conf

    kafka:
        container_name: flatagram_kafka
        image: wurstmeister/kafka
        ports:
          - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

    zookeeper:
        container_name: flatagram_zookeeper
        image: wurstmeister/zookeeper
        ports:
          - "2181:2181"
volumes:
  mysqldb: {}
