version: '3'
services:
  redis:
    image: redis
    container_name: 'redis'
    ports:
      - '6379:6379'

  kafka:
    hostname: malllag-kafka
    image: wurstmeister/kafka
    container_name: 'kafka'
    platform: linux/arm64
    ports:
      - '9092:9092'
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: 'zookeeper'
    platform: linux/amd64
    ports:
      - '2181:2181'

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: 'kafdrop'
    platform: linux/amd64
    restart: "no"
    ports:
      - "9001:9001"
    environment:
      KAFKA_BROKERCONNECT: "malllag-kafka:9092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
      SERVER_PORT: 9001
      MANAGEMENT_SERVER_PORT: 9001
    depends_on:
      - kafka

  mysql:
    image: mysql
    container_name: 'mysql'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: instagram
      MYSQL_USER: malllag
      MYSQL_PASSWORD: 1234
