spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flatagram?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: flatagram
    password: 1234
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    host: 127.0.0.1
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup
