server:
  port: 8080
  servlet:
    context-path: /instagram/api

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/instagram?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
    open-in-view: false

file:
  path: /Users/shark/Documents/GitHub/instagram-by-kotlin/shkim/instagram-by-kotlin/src/main/resources/image/